### ISSUE TITLE
Authentication security

### ISSUE THREAD

**Issue by ghzb** [spcnvdr/climatic#1]
I noticed that the login pages is using hard coded values for authentication.

We should probably use best practices or excluded authentication all together. 

What do you think?

-Zeb

**Comment by spcnvdr** [comment]
The original plan is to remove authentication completely because there is no sensitive information that will be exposed or stored by this project. This project started out as a template I made for future Flask/Python projects and the "authentication" feature is meant as a hold over until a proper authentication method is implemented (which I have created using an SQL server and Python 3). I think it would be a better idea to remove the "insecure" authentication method completely from the project. If you agree with the decision to remove all authentication or login features, reply to this comment and I will close this issue. I will mark this closed as soon as I remove all traces of the old code.

**Comment by spcnvdr** [comment]
Removed authentication and the login and logout routes. The templates still remain for now. I removed most of the code from main that implemented the authentication, but some code is still in main. I will remove the remaining code in the future. This issue is considered closed as the issue has been fixed/removed from the project.
